version: '3.8'
services:
  user-db:
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: user-db
    ports:
      - "5432:5432"
    volumes:
      - postgres:/var/lib/postgresql/data


  product-db:
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: product-db
    ports:
      - "5433:5432"
    volumes:
      - postgres:/var/lib/postgresql/data


volumes:
    postgres:
    
